/*
 * SevenSegmentMuxConfig.h
 *
 *  Created on: Jun 9, 2023
 *      Author: Ali Emad
 */

#ifndef HAL_OS_INC_SEVENSEGMENTMUX_SEVENSEGMENTMUXCONFIG_H_
#define HAL_OS_INC_SEVENSEGMENTMUX_SEVENSEGMENTMUXCONFIG_H_

#define configHOS_SEVEN_SEGMENT_EN							1
#define configHOS_SEVEN_SEGMENT_MUX_MAX_NUMBER_OF_DIGITS	4
#define configHOS_SEVEN_SEGMENT_MUX_MAX_NUMBER_OF_OBJECTS	5
#define configHOS_SEVEN_SEGMENT_MUX_UPDATE_TIME_MS			10

#endif /* HAL_OS_INC_SEVENSEGMENTMUX_SEVENSEGMENTMUXCONFIG_H_ */
